### ISSUE TITLE
Update documentation for consistency and clarification between 'document' vs 'message'

### ISSUE THREAD

**Issue by inadarei** [uber-hypermedia/specification#1]
_From @inadarei on September 16, 2014 7:10_

@see: https://github.com/mamund/media-types/issues/46#issuecomment-55702194

_Copied from original issue: mamund/media-types#47_

**Comment by mamund** [comment]
@inadarei 

right now, the only place "message" appears is in the description of the `value` property. the rest of the text uses "document."

i'm cool w/ changing those last two remaining uses of "message" to "document" to close this out.

cool?

**Comment by inadarei** [comment]
Fixed: https://github.com/uber-hypermedia/specification/commit/b6f4b76c991d1c5e0be204022fe50c7d9a4e1c39
