### ISSUE TITLE
clarify support for profiles in UBER

### ISSUE THREAD

**Issue by mamund** [uber-hypermedia/specification#18]
* inline? 
 * via LINK header?
 * via media type parameter?

combination of the three. order does not matter? discuss.

**Comment by mamund** [comment]
addressed in https://github.com/uber-hypermedia/specification/tree/issue-18 commit

**Comment by mamund** [comment]
looks good. closed.

**Comment by mamund** [comment]
this branch handles the mechanics of _how_ profiles are implemented.

we can tackle runtime aspects of profiles (scope, conflicts, etc.) in a new issue.

**Comment by inadarei** [comment]
Awesome. Makes sense.
