### ISSUE TITLE
Description field for the data element

### ISSUE THREAD

**Issue by inadarei** [uber-hypermedia/specification#2]
_From @inadarei on August 3, 2014 23:45_

In real-life forms fields typically aren't just title/value pairs, but frequently also contain "description" field, to provide context, explanation or hints in addition to the typically very short "title" field. I think "data" could use it as well. 

It may be often empty, but when you need it, you could really use it

Consider this example:

```json
{ 
        "name"    : "Profile Photo Upload",
        "rel"     : ["http://api.example.com/rels/profile-photo"],
        "url"     : "http://api.example.com/profile-photo",
        "action"  : "replace",
        "sending" : "multipart/form-data",
        "model"   : "{?user-id,photo}",
        "data"    : 
        [
          {
            "name"  : "user-id",
            "value"   : "User ID"
          },
          {
            "name"         : "photo",
            "value"          : "Profile Photo",
            "description"  : "Please provide PNG files with at least 300dpi resolution" 
           }
         ]
      }
```

_Copied from original issue: mamund/media-types#45_

**Comment by mamund** [comment]
@inadarei 

on this `description` attribute -- all cool for me. 

i assume this is about decorating `data` elements that are primarily values, but not sure.

your two examples:
 * https://github.com/uber-hypermedia/specification/issues/2#issuecomment-68026749
 * https://github.com/uber-hypermedia/specification/issues/2#issue-52796275

are very diff, BTW. one is for something *in addition to* a label (the first). the second is one *as a* label. i want to make sure we don't get confused on what we're doing or how we suggest this be used.

for the record, there are a handful of things in HTML-land that come close to this functionality:
 * `@alt`
 * `[label]`
 * `[legend]`
 * `@longdesc`
 * `@prompt`
 * `@summary`
 * `@title`

we should be clear on what we're doing here -- our primary aim. i *think* our goal is to offer the ability to associate prompts w/ data (for both input and display)  __*for humans*__.  we already have `id` and `name` and `rel` which as all _machines_ will need.  the next thing we need to be sure of is if we are doing this for just _value_ items (e.g. `HTML.LABEL`) or also for _link_ items (e.g. `HTML.A@title` or `HTML.IMG@alt`, etc.)

if we want to support _both_ we should pick a name and a general use-case that makes sense for both. and i'd like to avoid repeating my mistake w/ `url` and `model` -- i thought templating use would be mutually exclusive, but found out we wanted to template _both_ properties in the same control.

that's my $0.02

**Comment by inadarei** [comment]
@mamund, I agree with you 100%. I think @description should be considered as part of larger support for more expressive forms.

What I am doing in my example No. 1 has issues. Specifically, this example:

```json
{ 
  "name"    : "Profile Photo Upload",
  "rel"     : ["http://api.example.com/rels/profile-photo"],
  "url"     : "http://api.example.com/profile-photo",
  "action"  : "replace",
  "sending" : "multipart/form-data",
  "model"   : "{?user-id,photo}",
  "data"    : 
  [
    {
      "name"  : "user-id",
      "value"   : "User ID"
    },
    {
      "name"         : "photo",
      "value"          : "Profile Photo",
      "description"  : "Please provide PNG files with at least 300dpi resolution" 
     }
   ]
}
```

assumes that the inner data element "explains" the params of the model. But nowhere in UBER is that a normative representation of a behavior. In that specific API I was going to document the behavior in API-specific documentation. However, our appetite has increased since then, I think :) 

While discussing other issues closed last week, we've discussed a possibility of standardizing fuller support for forms, including: how form params can be documented in the message response itself.

**Comment by mamund** [comment]
so, is this `description` item only about `FORMS` support? that's kinda what my Q was above. 

let's make sure we agree on what we plan to be doing w/ `description`

FWIW, i think we have all we need for supporting `FORMS` for __*machines*__ already. Maybe we need more features for __*humans*__, tho (e.g. labels for values, inputs, and links).

**Comment by inadarei** [comment]
Fixed: https://github.com/uber-hypermedia/specification/commit/98ef1ce75c9f62a80a1033b86164f46b0a426b6a
